version: '3.8'

services:
  # User Service Database
  user-db:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  # Product Service Database
  product-db:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  # Order Service Database
  order-db:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

volumes:
  user_data:
  product_data:
  order_data: